# Generated by Django 3.1.7 on 2021-04-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='verify',
            field=models.IntegerField(default=999999),
        ),
    ]
