# Generated by Django 3.1.7 on 2021-04-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210421_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='enable',
        ),
    ]
