# Generated by Django 3.1.3 on 2021-04-23 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('gpio_num', models.IntegerField(default=0)),
                ('color', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(blank=True, default='', max_length=100)),
                ('onoff', models.BooleanField(default=False)),
                ('authenti_testing', models.CharField(blank=True, default='No authentication', max_length=100)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LEDs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['color'],
            },
        ),
    ]
