# Generated by Django 3.2 on 2021-07-03 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture', models.FloatField()),
                ('volumne', models.FloatField()),
                ('temperature', models.FloatField()),
                ('mode', models.CharField(choices=[('deault', 'default'), ('manual', 'manual')], max_length=10)),
                ('type', models.CharField(choices=[('watering', 'watering'), ('fan', 'fan')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_condition', to='controller.controller')),
            ],
        ),
    ]
