# Generated by Django 3.2 on 2021-07-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_auto_20210703_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioncondition',
            name='mode',
            field=models.CharField(choices=[('default', 'default'), ('manual', 'manual')], max_length=10),
        ),
    ]
