# Generated by Django 3.2 on 2021-07-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_warningcondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('environment', models.CharField(max_length=300)),
                ('livespan', models.FloatField()),
            ],
        ),
    ]
