# Generated by Django 3.2 on 2021-07-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0006_plants'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plants',
            new_name='Plant',
        ),
    ]
