# Generated by Django 3.2 on 2021-09-12 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0007_rename_plants_plant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electricity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.FloatField()),
                ('shift', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='actioncondition',
            old_name='volume',
            new_name='brightness',
        ),
        migrations.AddField(
            model_name='actioncondition',
            name='humidity',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='actioncondition',
            name='operator',
            field=models.CharField(choices=[('<', '<'), ('>', '<')], default='<', max_length=1),
        ),
        migrations.AddField(
            model_name='actioncondition',
            name='status',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=3),
        ),
        migrations.AddField(
            model_name='warningcondition',
            name='brightness',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='warningcondition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warningcondition',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='actioncondition',
            name='type',
            field=models.CharField(choices=[('watering', 'watering'), ('fan', 'fan'), ('light', 'light')], max_length=10),
        ),
        migrations.AlterField(
            model_name='warningcondition',
            name='humidity',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='warningcondition',
            name='moisture',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='warningcondition',
            name='temperature',
            field=models.FloatField(default=-1),
        ),
    ]
