# Generated by Django 3.2 on 2021-09-19 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0008_auto_20210912_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actioncondition',
            name='controller',
        ),
        migrations.DeleteModel(
            name='Electricity',
        ),
        migrations.DeleteModel(
            name='Plant',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
        migrations.RemoveField(
            model_name='warningcondition',
            name='user',
        ),
        migrations.DeleteModel(
            name='WaterStorage',
        ),
        migrations.DeleteModel(
            name='ActionCondition',
        ),
        migrations.DeleteModel(
            name='WarningCondition',
        ),
    ]
