# Generated by Django 3.2 on 2021-09-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0010_actioncondition_electricity_plant_track_warningcondition_waterstorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioncondition',
            name='operator',
            field=models.CharField(choices=[('<', '<'), ('>', '>')], default='<', max_length=1),
        ),
        migrations.AlterField(
            model_name='warningcondition',
            name='operator',
            field=models.CharField(choices=[('<', '<'), ('>', '>')], max_length=1),
        ),
    ]
