# Generated by Django 3.2 on 2021-10-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0013_warningcondition_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='max_humidity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plant',
            name='max_temp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plant',
            name='min_humidity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plant',
            name='min_temp',
            field=models.FloatField(default=0),
        ),
    ]
