# Generated by Django 3.2 on 2021-10-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0014_auto_20211022_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='test',
            field=models.FloatField(default=0),
        ),
    ]
