# Generated by Django 3.2 on 2021-10-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0015_plant_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image_test',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
