# Generated by Django 3.2 on 2021-10-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0016_plant_image_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='image_test',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='test',
        ),
    ]
