# Generated by Django 3.2 on 2021-10-22 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controller', '0017_auto_20211022_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsertoPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='User_plant', to='controller.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='User_plant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
