# Generated by Django 3.1.7 on 2021-04-21 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_auto_20210421_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensorID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('sensorName', models.CharField(max_length=30)),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
        migrations.CreateModel(
            name='Moisture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('value', models.FloatField()),
                ('sensorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enviroment.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Humid_Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('heatIndex', models.FloatField(default=0)),
                ('sensorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enviroment.sensor')),
            ],
        ),
    ]
