# Generated by Django 3.1.3 on 2021-04-23 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_client_enable'),
        ('enviroment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humid_temp',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='humid_temp', to='enviroment.sensor'),
        ),
        migrations.AlterField(
            model_name='moisture',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moisture', to='enviroment.sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='client.client'),
        ),
    ]
