# Generated by Django 3.1.3 on 2021-04-30 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enviroment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='auth.user'),
        ),
    ]
