# Generated by Django 3.1.7 on 2021-04-21 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210421_2218'),
        ('enviroment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humid_temp',
            name='sensorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='humid_temp', to='enviroment.sensor'),
        ),
        migrations.AlterField(
            model_name='moisture',
            name='sensorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moisture', to='enviroment.sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='clientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='client.client'),
        ),
    ]
