# Generated by Django 3.2 on 2021-07-02 23:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enviroment', '0002_remove_plantimg_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumidTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('heatIndex', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='moisture',
            old_name='value',
            new_name='moisture',
        ),
        migrations.RenameField(
            model_name='moisture',
            old_name='created',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='plantimg',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='plantimg',
            old_name='created',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='sensor',
            name='interval',
            field=models.DurationField(default=datetime.timedelta(seconds=30)),
        ),
        migrations.AlterField(
            model_name='moisture',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moisture', to='enviroment.sensor'),
        ),
        migrations.AlterField(
            model_name='plantimg',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantimg', to='enviroment.sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Humid_Temp',
        ),
        migrations.AddField(
            model_name='humidtemp',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='humidtemp', to='enviroment.sensor'),
        ),
    ]
