# Generated by Django 3.1.7 on 2021-04-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviroment', '0002_auto_20210329_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='humidity',
            name='sensorId',
            field=models.CharField(default='a', max_length=10),
        ),
        migrations.AddField(
            model_name='temperature',
            name='sensorId',
            field=models.CharField(default='a', max_length=10),
        ),
    ]
