# Generated by Django 3.2 on 2021-05-15 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enviroment', '0002_auto_20210430_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera', to='enviroment.sensor')),
            ],
        ),
    ]
