# Generated by Django 3.2 on 2021-05-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviroment', '0003_plantimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantimg',
            name='img',
            field=models.ImageField(upload_to='plant_images/'),
        ),
    ]
