# Generated by Django 3.1.7 on 2021-04-02 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enviroment', '0003_auto_20210402_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humidity',
            name='sensorId',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='sensorId',
        ),
    ]
