# Generated by Django 3.1.7 on 2021-04-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviroment', '0004_auto_20210402_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='humidity',
            name='sensorId',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='temperature',
            name='sensorId',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
