# Generated by Django 3.2 on 2021-07-14 08:11

from django.db import migrations, models
import django.db.models.deletion
import enviroment.models


class Migration(migrations.Migration):

    dependencies = [
        ('enviroment', '0004_auto_20210703_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantYoloCropImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=enviroment.models.plantimgcrophelper)),
                ('prob', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('plantimg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_yolo_crop', to='enviroment.plantimg')),
            ],
        ),
    ]
