# Generated by Django 3.2 on 2021-05-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviroment', '0004_alter_plantimg_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantimg',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
