# Generated by Django 3.1.7 on 2021-04-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviroment', '0005_auto_20210402_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Humid_Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('humidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('heatIndex', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Moisture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensorID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('sensorName', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Humidity',
        ),
        migrations.DeleteModel(
            name='Temperature',
        ),
    ]
