# Generated by Django 3.1.3 on 2021-04-21 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210421_2218'),
        ('enviroment', '0006_auto_20210421_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='clientID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
