# Generated by Django 3.1.3 on 2021-04-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviroment', '0010_auto_20210422_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moisture',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
